### ISSUE TITLE
Why this app can't be executed in Firefox, technically speaking?

### ISSUE THREAD

**Issue by q2dg** [antiboredom/zoom-escaper#3]
I mean..which is the API that is in available in Chrome but it isn't in Firefox?
It could be difficult to port it?
Thanks!

**Comment by antiboredom** [comment]
It's [setSinkId function](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId) which allows you to chose an audio output device. This can actually be enabled in Firefox by setting a flag.

I'm also using the [permissions query](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query) which isn't fully compatible in firefox. I'd be happy to change this though since it's not fundamental to the app working.

I would love to get it working in Firefox (especially because it's my main browser) but not sure how to get around the setSinkId issue!

**Comment by q2dg** [comment]
Thanks a lot for your kind explanation!
Please feel free to close this issue if you consider it, or leave it open as a reminder.
Thanks!

**Comment by MPeti1** [comment]
Since setSinkId can be enabled in a way that's not really convoluted, I think it would be a good idea to include instructions for that too, and instead of blocking by user agent, block by checking if the that API function is working. I already have it enabled in my conferencing browser profile to make some services work.

**Comment by MPeti1** [comment]
@antiboredom why was this issue closed? As far as I can tell, the issue has not been resolved

**Comment by antiboredom** [comment]
Hi @MPeti1 - it's actually not blocking by user agent -- it will work in any browser that has the setSinkId and the permissions query functions.

**Comment by mhalano** [comment]
That is true. I enabled the option and seems to work (I didn't tested on the field, just the webpage).
![image](https://user-images.githubusercontent.com/6025031/131230863-bc5b4022-be27-4f08-9f5a-ecf26f5fb450.png)
![image](https://user-images.githubusercontent.com/6025031/131230867-b77c3272-1ca6-49e9-bbef-2a548349fa4a.png)

**Comment by mhalano** [comment]
I'm using Linux, BTW

**Comment by MPeti1** [comment]
Oh, the permissions query.. ok, I understand now
